{
  "name": "Zoran-Injecteur-Total-Generique",
  "version": "1.0",
  "license": "MIT",
  "created": "2025-08-26",
  "maintainers": [
    {
      "name": "Fr\u00e9d\u00e9ric Tabary",
      "email": "tabary01@gmail.com"
    }
  ]
}